apiVersion: v1
kind: ConfigMap
metadata:
  name: idbi-apim-msr1-config
  namespace: nsp-idbi-apim-prod
data:

  application.properties: |
    #Sample Generated Template
    #Fri Oct 08 14:42:43 IST 2021
    jdbc.MWSUser.dbURL=jdbc\:wm\:oracle\://10.142.15.231\:1521;serviceName\=ESBPROD
    jdbc.MWSUser.password={AES}dh0UoYRPbCqR23pGjAi1pg==
    jdbc.MWSUser.userid=mwsprod
    jms.DEFAULT_IS_JMS_CONNECTION.clientID=MSR1_IS_JMS_CLIENT
    jms.PE_NONTRANSACTIONAL_ALIAS.clientID=MSR1_PE
    jndi.DEFAULT_IS_JNDI_PROVIDER.providerURL=nsp\://localhost\:9000
    messaging.IS_UM_CONNECTION.CLIENTPREFIX=msr1
    messaging.IS_UM_CONNECTION.type=UM
    messaging.IS_UM_CONNECTION.url=nsp\://localhost\:9000
    settings.watt.server.compile=/opt/softwareag/jvm/jvm/bin/javac -classpath {0} -d {1} {2}
    settings.watt.server.auth.samlResolver=https://idbi-apim-mws-svc-h.nsp-idbi-apim-prod.svc.cluster.local/services/SAML
    settings.watt.server.threadPool=500
    settings.watt.net.jsse.client.disabledProtocols=SSLv2Hello,SSLv3,TLSv1,TLSv1.1
    settings.watt.net.jsse.server.disabledProtocols=SSLv2Hello,SSLv3,TLSv1,TLSv1.1
    user.Administrator.password={AES}Z4F7+5o18hGDOcF5Tkm1Fw==
    user.Developer.password={AES}Z4F7+5o18hGDOcF5Tkm1Fw==
    user.Replicator.password={AES}Z4F7+5o18hGDOcF5Tkm1Fw==
    truststore.DEFAULT_JVM_TRUSTSTORE.ksLocation=../jvm/jvm/jre/lib/security/cacerts
    truststore.DEFAULT_JVM_TRUSTSTORE.ksPassword={AES}z/+xVlzI9T/Dfo7Su4lrCQ==
    truststore.istruststore.ksLocation=../common/conf/truststore.jks
    truststore.istruststore.ksPassword={AES}5Sk2kzZpiNfTWcyc6SqmOqdfMb/wujaO5BwCaBr9GW0=
    keystore.iskeystore.keyAlias.idbibank.keyAliasPassword={AES}dg0Q8WN9gC7SIBnwlJXC3VouxNw/LIjo/4QuGw6nvb0=
    keystore.iskeystore.ksLocation=../common/conf/keystore.jks
    keystore.iskeystore.ksPassword={AES}dg0Q8WN9gC7SIBnwlJXC3VouxNw/LIjo/4QuGw6nvb0=

  setenv.sh:  |
    #!/bin/sh

    ##############################################################################
    #
    # This file contains parameters that can be modified by users.
    #
    ##############################################################################

    ## ---- SET INITIALLY BY THE INSTALLER ----

    BINDIR=`dirname $0`
    GLOBAL_SETENV=${BINDIR}/../../install/bin/setenv.sh
    APP_NAME="Software AG Microservices Runtime"

    OLD_JAVA_HOME=$JAVA_HOME
    if [ -r "$GLOBAL_SETENV" ]; then
    	. "$GLOBAL_SETENV"
    fi

    if [ "x$JRE_HOME" = "x" ]; then
    	JAVA_DIR=$OLD_JAVA_HOME
    else
    	JAVA_DIR=$JRE_HOME
    fi

    ##############################################################################
    #
    # This file contains parameters that can be modified by users.
    #
    ##############################################################################

    if [ "x$JAVA_MIN_MEM" = "x" ]; then
    	JAVA_MIN_MEM=1024M
    fi

    if [ "x$JAVA_MAX_MEM" = "x" ]; then
    	JAVA_MAX_MEM=1024M
    fi

    JAVA_MEMSET="-ms${JAVA_MIN_MEM} -mx${JAVA_MAX_MEM}"

    JAVA_OPT_PREFER_IP4V="-Djava.net.preferIPv4Stack=true"

    ##############################################################################
    #
    # Items in PREPENDCLASSES will be added to the classpath right after the server.jar
    # Items in the APPENDCLASSES will be added to the absolute end of the CLASSPATH
    #
    ##############################################################################

    PREPENDCLASSES=
    APPENDCLASSES=

    ##############################################################################
    #
    # Items in PREPEND_SYSTEM_CLASSPATH will be added to the classpath before proxy.jar
    # Items in APPEND_SYSTEM_CLASSPATH will be added to the absolute end of the CLASSPATH
    #
    ##############################################################################

    PREPEND_SYSTEM_CLASSPATH=
    APPEND_SYSTEM_CLASSPATH=

    if [ "x$SHUTDOWN_WAIT" = "x" ]; then
    	SHUTDOWN_WAIT=300
    fi

    ##############################################################################
    #
    # Enter your custom Java options in the variable JAVA_CUSTOM_OPTS
    # e.g. JAVA_CUSTOM_OPTS="-Dmy.prop1=value1 -Dmy.prop2=value2"
    ##############################################################################

    JAVA_CUSTOM_OPTS="${JAVA_CUSTOM_OPTS} ${JAVA_DEBUGGER_OPTS}"

    ##############################################################################
    #
    # Java options for Remote Debugging, JMX, and Profiling
    #
    ##############################################################################

    JMX_ENABLED=false
    PROFILER_ENABLED=false

    JMX_PORT=9192

    JAVA_JMX_OPTS="-Dcom.sun.management.jmxremote.port=${JMX_PORT} -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
    JAVA_PROFILER_OPTS="-javaagent:lib/jars/profiler-agent.jar=log=logs/profiler.log,level=2"

    if [ "$JMX_ENABLED" = "true" ]; then
    	JAVA_CUSTOM_OPTS="${JAVA_CUSTOM_OPTS} ${JAVA_JMX_OPTS}"
    fi

    if [ "$PROFILER_ENABLED" = "true" ]; then
    		JAVA_CUSTOM_OPTS="${JAVA_CUSTOM_OPTS} ${JAVA_PROFILER_OPTS}"
    fi