apiVersion: v1
kind: ConfigMap
metadata:
  name: idbi-apim-apigw-config
  namespace: nsp-idbi-apim-prod
data:

  application.properties: |
    #Sample Generated Template
    #Fri Oct 08 10:30:28 IST 2021
    jdbc.ISInternal.dbURL=jdbc\:wm\:oracle\://10.142.15.231\:1521;serviceName\=ESBPROD
    jdbc.ISInternal.password={AES}YzFuDHxNhNs+ttkCQO5XxA==
    jdbc.ISInternal.userid=apigwprod
    settings.watt.server.cluster.aware=true
    settings.watt.server.cluster.name=APIGatewayTSACluster
    settings.watt.server.cluster.tsaURLs=idbi-apim-tsa-cluster-0.idbi-apim-tsa-svc-h.nsp-idbi-apim-prod.svc.cluster.local\:9510,idbi-apim-tsa-cluster-1.idbi-apim-tsa-svc-h.nsp-idbi-apim-prod.svc.cluster.local\:9510

  custom_wrapper.conf:  |
    #encoding=UTF-8
    wrapper.app.parameter.2=4
    wrapper.app.parameter.5=-service
    wrapper.app.parameter.6=sagis107
    wrapper.java.additional.100=-server
    wrapper.java.additional.101=-Dorg.apache.xml.dtm.DTMManager=org.apache.xml.dtm.ref.DTMManagerDefault
    wrapper.java.additional.102=-Djavax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom=com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl
    wrapper.java.additional.103=-Dcom.webmethods.sc.auditing.Use80TableFormat=true
    wrapper.java.additional.104=-Dsun.lang.ClassLoader.allowArraySyntax=true
    wrapper.java.additional.105=-XX:+UseOpenJSSE
    wrapper.java.additional.201=-DWM_HOME=/opt/softwareag
    wrapper.java.additional.202=-Dwatt.server.prepend.classes=/opt/softwareag/common/lib/wm-converters.jar
    wrapper.java.additional.203=-Dwatt.server.append.classes=
    wrapper.java.additional.204=-Dlog4j.configurationFile="/opt/softwareag/profiles/IS_default/configuration/logging/log4j2.properties,.tc.custom.log4j2.properties"
    wrapper.java.additional.204.stripquotes=TRUE
    wrapper.java.additional.301=-Dorg.tanukisoftware.wrapper.WrapperStartStopApp.passthroughMode=START
    wrapper.java.additional.302=-Djava.awt.headless=true
    wrapper.java.additional.303=-DLog4jContextSelector=org.apache.logging.log4j.core.selector.BasicContextSelector
    wrapper.java.classpath.3=/opt/softwareag/common/lib/wm-converters.jar
    wrapper.java.initmemory=4096
    wrapper.java.library.path.11=/opt/softwareag/IntegrationServer/instances/default/lib
    wrapper.java.library.path.append_system_path=TRUE
    wrapper.java.maxmemory=4096
    wrapper.jvm_exit.timeout=300
    wrapper.on_exit.42=RESTART
    wrapper.ping.timeout=300
    wrapper.restart.reload_configuration=TRUE
    wrapper.shutdown.timeout=300
    wrapper.single_invocation=TRUE
    wrapper.working.dir=/opt/softwareag/IntegrationServer/instances/default
    wrapper.java.additional.106=-Djava.security.properties=config/security/webm_override_java.security
    wrapper.java.additional.999=-Dtest.cluster.withDerby=true


